### ISSUE TITLE
loboeevolution-3.0.jar does not work with Java 8, 11, 17 and 18 (built or downloaded)

### ISSUE THREAD

**Issue by dbonner** [LoboEvolution/LoboEvolution#75]
Hi,
I'm running Windows 11 Pro.
I actually tried building using JDK 8, 11, 17 and 18.
I also tried running the file that can now be downloaded (loboevolution-3.0.jar) using JRE 8, 11, 17 and 18.

With jre 8 and 11, the GUI loads up, but I can not surf anywhere because I get:

Jul 22, 2022 6:11:09 PM org.loboevolution.html.gui.HtmlPanel createHtmlPanel
SEVERE: Server returned HTTP response code: 403 for URL: https://www.google.com/search?q=github
java.io.IOException: Server returned HTTP response code: 403 for URL: https://www.google.com/search?q=github
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1914)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1512)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
        at org.loboevolution.net.HttpNetwork.getGzipStream(HttpNetwork.java:65)
        at org.loboevolution.net.HttpNetwork.getInputStream(HttpNetwork.java:102)
        at org.loboevolution.net.HttpNetwork.openConnectionCheckRedirects(HttpNetwork.java:252)
        at org.loboevolution.html.gui.HtmlPanel.createPanel(HtmlPanel.java:600)
        at org.loboevolution.html.gui.HtmlPanel.createHtmlPanel(HtmlPanel.java:590)
        at org.loboevolution.http.NavigationManager.getHtmlPanelSearch(NavigationManager.java:110)
        at org.loboevolution.welcome.LoginButton$1.mousePressed(LoginButton.java:95)
        at java.awt.Component.processMouseEvent(Component.java:6536)
        at javax.swing.JComponent.processMouseEvent(JComponent.java:3318)
        at java.awt.Component.processEvent(Component.java:6304)
        at java.awt.Container.processEvent(Container.java:2239)
        at java.awt.Component.dispatchEventImpl(Component.java:4889)
        at java.awt.Container.dispatchEventImpl(Container.java:2297)
        at java.awt.Component.dispatchEvent(Component.java:4711)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
        at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4532)
        at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
        at java.awt.Container.dispatchEventImpl(Container.java:2283)
        at java.awt.Window.dispatchEventImpl(Window.java:2746)
        at java.awt.Component.dispatchEvent(Component.java:4711)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
        at java.awt.EventQueue$4.run(EventQueue.java:733)
        at java.awt.EventQueue$4.run(EventQueue.java:731)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at org.loboevolution.welcome.LoginButton$1.mousePressed(LoginButton.java:97)
        at java.awt.Component.processMouseEvent(Component.java:6536)
        at javax.swing.JComponent.processMouseEvent(JComponent.java:3318)
        at java.awt.Component.processEvent(Component.java:6304)
        at java.awt.Container.processEvent(Container.java:2239)
        at java.awt.Component.dispatchEventImpl(Component.java:4889)
        at java.awt.Container.dispatchEventImpl(Container.java:2297)
        at java.awt.Component.dispatchEvent(Component.java:4711)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
        at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4532)
        at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
        at java.awt.Container.dispatchEventImpl(Container.java:2283)
        at java.awt.Window.dispatchEventImpl(Window.java:2746)
        at java.awt.Component.dispatchEvent(Component.java:4711)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
        at java.awt.EventQueue$4.run(EventQueue.java:733)
        at java.awt.EventQueue$4.run(EventQueue.java:731)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

With jre 17 and 18, the GUI fails to load and I immediately get returned to the command prompt after this error:

Exception in thread "AWT-EventQueue-0" java.lang.IllegalAccessError: class org.sexydock.tabs.jhrome.JhromeTabbedPaneUI (in unnamed module @0x4a2f3c36) cannot access class sun.swing.DefaultLookup (in module java.desktop) because module java.desktop does not export sun.swing to unnamed module @0x4a2f3c36
        at org.sexydock.tabs.jhrome.JhromeTabbedPaneUI.getInputMap(JhromeTabbedPaneUI.java:1096)
        at org.sexydock.tabs.jhrome.JhromeTabbedPaneUI.installKeyboardActions(JhromeTabbedPaneUI.java:1085)
        at org.sexydock.tabs.jhrome.JhromeTabbedPaneUI.init(JhromeTabbedPaneUI.java:246)
        at org.sexydock.tabs.jhrome.JhromeTabbedPaneUI.installUI(JhromeTabbedPaneUI.java:160)
        at java.desktop/javax.swing.JComponent.setUI(JComponent.java:730)
        at java.desktop/javax.swing.JTabbedPane.setUI(JTabbedPane.java:249)
        at org.loboevolution.tab.DnDTabbedPane.init(DnDTabbedPane.java:55)
        at org.loboevolution.tab.DnDTabbedPane.<init>(DnDTabbedPane.java:51)
        at org.loboevolution.component.BrowserPanel.<init>(BrowserPanel.java:58)
        at org.loboevolution.component.BrowserFrame.<init>(BrowserFrame.java:68)
        at org.loboevolution.init.GuiInit.createAndShowGui(GuiInit.java:131)
        at org.loboevolution.init.GuiInit.install(GuiInit.java:147)
        at org.loboevolution.init.PlatformInit.lambda$main$0(PlatformInit.java:44)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90

All the best,
Daniel

**Comment by oswetto** [comment]
Hello @dbonner thanks for test. Loboevolution is working progress and work only with simple site.
You ca test url https://www.w3schools.com/html/default.asp for example

**Comment by dbonner** [comment]
Hi Oswetto, I really like the ideas behind your project. Sadly, loboevolution 3 still gives the 404 error with the test url. I can run JavaFXBrowser 3.5.1 with no problems.

**Comment by Ygarr** [comment]
May be need to consider all the troubles which can appear while migrating project to java18? To make a plan?

**Comment by oswetto** [comment]
Fixed JhromeTabbedPaneUI  error with 9, 11, 14, 17 and 18

**Comment by Ygarr** [comment]
mvn install -DskipTests=true - Build Success for now
And looks running good  
![image](https://user-images.githubusercontent.com/14309871/185644256-90c1de44-a0a4-498f-9c92-99e40036a761.png)

**Comment by oswetto** [comment]
Fixed in last commit. Thanks at all for test
