### ISSUE TITLE
Cannot run with jar

### ISSUE THREAD

**Issue by Ygarr** [LoboEvolution/LoboEvolution#77]
```
 java -jar .\loboevolution-3.0.jar
Exception in thread "AWT-EventQueue-0" java.lang.IllegalAccessError: class org.sexydock.tabs.jhrome.JhromeTabbedPaneUI (in unnamed module @0x43e9b0d5) cannot access class sun.swing.DefaultLookup (in module java.desktop) because module java.desktop does not export sun.swing to unnamed module @0x43e9b0d5
        at org.sexydock.tabs.jhrome.JhromeTabbedPaneUI.getInputMap(JhromeTabbedPaneUI.java:1096)
        at org.sexydock.tabs.jhrome.JhromeTabbedPaneUI.installKeyboardActions(JhromeTabbedPaneUI.java:1085)
        at org.sexydock.tabs.jhrome.JhromeTabbedPaneUI.init(JhromeTabbedPaneUI.java:246)
        at org.sexydock.tabs.jhrome.JhromeTabbedPaneUI.installUI(JhromeTabbedPaneUI.java:160)
        at java.desktop/javax.swing.JComponent.setUI(JComponent.java:740)
        at java.desktop/javax.swing.JTabbedPane.setUI(JTabbedPane.java:250)
        at org.loboevolution.tab.DnDTabbedPane.init(DnDTabbedPane.java:55)
        at org.loboevolution.tab.DnDTabbedPane.<init>(DnDTabbedPane.java:51)
        at org.loboevolution.component.BrowserPanel.<init>(BrowserPanel.java:58)
        at org.loboevolution.component.BrowserFrame.<init>(BrowserFrame.java:68)
        at org.loboevolution.init.GuiInit.createAndShowGui(GuiInit.java:131)
        at org.loboevolution.init.GuiInit.install(GuiInit.java:147)
        at org.loboevolution.init.PlatformInit.lambda$main$0(PlatformInit.java:44)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by oswetto** [comment]
You can try with java8?

**Comment by Ygarr** [comment]
Already installed 11, 17, 18... may be  make Lobo a little more modern. Or Java 8 have some advantages?
Even minecraft created  11 years ago need java11...

**Comment by oswetto** [comment]
Fixed in last commit. Thansk for you test
