### ISSUE TITLE
Cannot Run loboevolution-3.0.jar

### ISSUE THREAD

**Issue by nsiatras** [LoboEvolution/LoboEvolution#80]
Hello,

I just download loboevolution-3.0.jar and I used the java -jar loboevolution-3.0.jar to run it.
The application starts and "installs" the browser but after a few moments the following error comes up
```
Exception in thread "AWT-EventQueue-0" java.lang.IllegalAccessError: class org.sexydock.tabs.jhrome.JhromeTabbedPaneUI (in unnamed module @0x1a5c22bf) cannot access class sun.swing.DefaultLookup (in module java.desktop) because module java.desktop does not export sun.swing to unnamed module @0x1a5c22bf
        at org.sexydock.tabs.jhrome.JhromeTabbedPaneUI.getInputMap(JhromeTabbedPaneUI.java:1096)
        at org.sexydock.tabs.jhrome.JhromeTabbedPaneUI.installKeyboardActions(JhromeTabbedPaneUI.java:1085)
        at org.sexydock.tabs.jhrome.JhromeTabbedPaneUI.init(JhromeTabbedPaneUI.java:246)
        at org.sexydock.tabs.jhrome.JhromeTabbedPaneUI.installUI(JhromeTabbedPaneUI.java:160)
        at java.desktop/javax.swing.JComponent.setUI(JComponent.java:730)
        at java.desktop/javax.swing.JTabbedPane.setUI(JTabbedPane.java:249)
        at org.loboevolution.tab.DnDTabbedPane.init(DnDTabbedPane.java:55)
        at org.loboevolution.tab.DnDTabbedPane.<init>(DnDTabbedPane.java:51)
        at org.loboevolution.component.BrowserPanel.<init>(BrowserPanel.java:58)
        at org.loboevolution.component.BrowserFrame.<init>(BrowserFrame.java:68)
        at org.loboevolution.init.GuiInit.createAndShowGui(GuiInit.java:131)
        at org.loboevolution.init.GuiInit.install(GuiInit.java:147)
        at org.loboevolution.init.PlatformInit.lambda$main$0(PlatformInit.java:44)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

I am using the following JDK
```
openjdk version "17.0.5" 2022-10-18
OpenJDK Runtime Environment GraalVM CE 22.3.0 (build 17.0.5+8-jvmci-22.3-b08)
OpenJDK 64-Bit Server VM GraalVM CE 22.3.0 (build 17.0.5+8-jvmci-22.3-b08, mixed mode, sharing)
```

**Comment by oswetto** [comment]
Hello @nsiatras 3.0 version was compatible only with java 8. 
I've release 3.1 with the fix.
Thansk for your test
